
TESTS = simple function math concrete_return uniform_test
TESTS += cfg_test cfg_search_test conditional

clean:
	rm -f idcount stmtcount funcount cfg cfg_branches cfg_func_map branches
	rm -f *.i *.cil.c *.o *~
	rm -f coverage input szd_execution yices_log
	rm -f $(TESTS)
