val doCheck : bool ref
val strictChecking : bool ref
val logCalls : bool ref
val logWrites : bool ref
val doPartial : bool ref
val doSimpleMem : bool ref
val doOneRet : bool ref
val doStackGuard : bool ref
val doHeapify : bool ref
val makeCFG : bool ref
val printStats : bool ref
val sliceGlobal : bool ref
val printStages : bool ref
val doCxxPP : bool ref
val libDir : string ref
val dumpFCG : bool ref
